// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCJPf3XhFAiFGH2fCV62a41RlryJ7JhDks',
    appId: '1:593380721659:web:3ddebb73dff4a47ddc415e',
    messagingSenderId: '593380721659',
    projectId: 'code-camp-flutter-b231a',
    authDomain: 'code-camp-flutter-b231a.firebaseapp.com',
    storageBucket: 'code-camp-flutter-b231a.appspot.com',
    measurementId: 'G-KL6ES7XT8M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDin3It9e190_iMo8Vk5Ce7uZ1tYV8zlHM',
    appId: '1:593380721659:android:375cf1d411c5dd13dc415e',
    messagingSenderId: '593380721659',
    projectId: 'code-camp-flutter-b231a',
    storageBucket: 'code-camp-flutter-b231a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB778uHomdsR5odOW0MRewB8LJQ-nAyQCQ',
    appId: '1:593380721659:ios:b6242b58105567e0dc415e',
    messagingSenderId: '593380721659',
    projectId: 'code-camp-flutter-b231a',
    storageBucket: 'code-camp-flutter-b231a.appspot.com',
    iosBundleId: 'com.example.tictactoe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB778uHomdsR5odOW0MRewB8LJQ-nAyQCQ',
    appId: '1:593380721659:ios:e8f39dc5e401e841dc415e',
    messagingSenderId: '593380721659',
    projectId: 'code-camp-flutter-b231a',
    storageBucket: 'code-camp-flutter-b231a.appspot.com',
    iosBundleId: 'com.example.tictactoe.RunnerTests',
  );
}
